/**
 * Service Navigation Component
 * Generated by Cursor
 */

'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';

export default function ServiceNavigation() {
  const pathname = usePathname();
  const isPostPage = pathname?.startsWith('/posts/');

  if (!isPostPage) {
    return null;
  }

  return (
    <div className="govuk-service-navigation">
      <div className="govuk-width-container">
        <div className="govuk-service-navigation__container">
          <span className="govuk-service-navigation__service-name">
            <Link href="/" className="govuk-service-navigation__link">
              BTMS news and guidance
            </Link>
          </span>
        </div>
      </div>
    </div>
  );
}

