/**
 * Bootstrap function to enable public permissions
 * Generated by Cursor
 */

export default {
  /**
   * An asynchronous register function that runs before
   * your application is initialized.
   */
  register(/* { strapi } */) {},

  /**
   * An asynchronous bootstrap function that runs before
   * your application gets started.
   */
  async bootstrap({ strapi }) {
    // Enable public access to content types
    const publicRole = await strapi
      .query('plugin::users-permissions.role')
      .findOne({ where: { type: 'public' } });

    if (publicRole) {
      const contentTypes = ['post', 'service', 'tag', 'team'];
      const actions = ['find', 'findOne'];
      
      for (const contentType of contentTypes) {
        for (const action of actions) {
          const permission = await strapi.query('plugin::users-permissions.permission').findOne({
            where: {
              role: publicRole.id,
              action: `api::${contentType}.${contentType}.${action}`,
            },
          });
          
          if (permission && !permission.enabled) {
            await strapi.query('plugin::users-permissions.permission').update({
              where: { id: permission.id },
              data: { enabled: true },
            });
          }
        }
      }
      
      console.log('✅ Public permissions enabled for all content types');
    }
  },
};
