/**
 * Home Page
 * Generated by Cursor
 */

import Link from 'next/link';
import { getPosts } from '@/lib/strapi';
import { format } from 'date-fns';

export default async function Home() {
  let posts = [];
  let error = null;
  
  try {
    posts = await getPosts();
  } catch (e) {
    error = 'Unable to load posts. Make sure Strapi is running.';
    console.error('Error fetching posts:', e);
  }

  return (
    <>
      <h1 className="govuk-heading-xl">Design Histories</h1>
      
      <p className="govuk-body-l">
        Design histories document the design decisions made during the development of DEFRA digital services.
      </p>

      <div className="govuk-inset-text">
        <p>
          This is a design history platform for DEFRA teams to share their design work, 
          iterations, and decisions in the open.
        </p>
      </div>

      {error && (
        <div className="govuk-error-summary" role="alert">
          <h2 className="govuk-error-summary__title">
            There is a problem
          </h2>
          <div className="govuk-error-summary__body">
            <p>{error}</p>
            <p>To get started:</p>
            <ol className="govuk-list govuk-list--number">
              <li>Start Strapi: <code>cd backend && npm run develop</code></li>
              <li>Create your first admin user at http://localhost:1337/admin</li>
              <li>Configure API permissions in Settings → Roles → Public</li>
              <li>Add some content in Content Manager</li>
            </ol>
          </div>
        </div>
      )}

      {posts.length > 0 ? (
        <>
          <h2 className="govuk-heading-l">Latest posts</h2>
          <ul className="post-list">
            {posts.map((post: any) => (
              <li key={post.id} className="post-list__item">
                <h3 className="govuk-heading-m post-list__title">
                  <Link 
                    href={`/posts/${post.slug}`}
                    className="govuk-link"
                  >
                    {post.title}
                  </Link>
                </h3>
                <p className="post-list__meta">
                  {post.publishDate && format(new Date(post.publishDate), 'd MMMM yyyy')}
                  {post.service?.title && ` • ${post.service.title}`}
                  {post.author && ` • by ${post.author}`}
                </p>
                <p className="govuk-body">{post.description}</p>
              </li>
            ))}
          </ul>
        </>
      ) : !error && (
        <div className="govuk-inset-text">
          <p>No posts yet. Log in to Strapi to create your first post.</p>
        </div>
      )}
    </>
  );
}

