/**
 * Preview API Route
 * Enables draft mode for content preview
 * Generated by Cursor
 */

import { draftMode } from 'next/headers';
import { redirect } from 'next/navigation';
import { NextRequest } from 'next/server';

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  
  // Get parameters from the URL
  const secret = searchParams.get('secret');
  const slug = searchParams.get('slug');
  const status = searchParams.get('status');

  // Verify the secret
  if (secret !== process.env.PREVIEW_SECRET) {
    return new Response('Invalid token', { status: 401 });
  }

  // If no slug provided, redirect to homepage
  if (!slug) {
    return new Response('Missing slug parameter', { status: 400 });
  }

  // Enable Next.js Draft Mode
  const draft = await draftMode();
  draft.enable();

  // Redirect to the path from the fetched post
  // We pass the status as a query parameter to help with data fetching
  const redirectUrl = `/posts/${slug}${status === 'draft' ? '?preview=true' : ''}`;
  
  redirect(redirectUrl);
}
