/**
 * Script to create a new post via Strapi API
 * Generated by Cursor
 * 
 * Usage: node scripts/create-post.js
 */

const STRAPI_URL = process.env.STRAPI_URL || 'http://localhost:1337';
const STRAPI_TOKEN = process.env.STRAPI_TOKEN || ''; // Leave empty for development

async function createPost(postData) {
  const response = await fetch(`${STRAPI_URL}/api/posts`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...(STRAPI_TOKEN && { 'Authorization': `Bearer ${STRAPI_TOKEN}` }),
    },
    body: JSON.stringify({ data: postData }),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to create post: ${response.statusText}\n${error}`);
  }

  return response.json();
}

// Example post data
const newPost = {
  heading: 'BTMS maintenance scheduled for 15 November 2025',
  slug: 'btms-maintenance-november-2025',
  description: 'BTMS will be undergoing planned maintenance on 15 November 2025 from 2am to 4am. During this time, the service will be unavailable.',
  content: `## What's happening

BTMS will be temporarily unavailable on **15 November 2025 from 2am to 4am** while we carry out essential maintenance work.

## What this means for you

During the maintenance window:

- You will not be able to access BTMS
- No pre-notifications can be submitted
- No matching will take place
- Reporting features will be unavailable

## What you need to do

- Plan your pre-notifications to be submitted before or after the maintenance window
- If you have urgent clearances, please submit them before 2am on 15 November
- Check this page after 4am to confirm the service has been restored

## Need help?

If you have any questions about this maintenance, please contact your local BTMS administrator.`,
  publishDate: new Date().toISOString(),
  author: 'BTMS Support Team',
  publishedAt: new Date().toISOString(), // This publishes the post immediately
  // service: 1, // Uncomment and add service ID if needed
  // tags: [1, 2], // Uncomment and add tag IDs if needed
};

// Run the script
async function main() {
  try {
    console.log('Creating new post...\n');
    console.log('Post data:', JSON.stringify(newPost, null, 2));
    console.log('\n---\n');
    
    const result = await createPost(newPost);
    
    console.log('✅ Post created successfully!');
    console.log('\nPost details:');
    console.log('- ID:', result.data.id);
    console.log('- Heading:', result.data.attributes.heading);
    console.log('- Slug:', result.data.attributes.slug);
    console.log('\nView post at: http://localhost:3000/posts/' + result.data.attributes.slug);
  } catch (error) {
    console.error('❌ Error creating post:', error.message);
    process.exit(1);
  }
}

main();

