/**
 * Post Detail Page
 * Generated by Cursor
 */

import { notFound } from 'next/navigation';
import Link from 'next/link';
import { getPost } from '@/lib/strapi';
import { format } from 'date-fns';
import { marked } from 'marked';

export default async function PostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = await getPost(slug);

  if (!post) {
    notFound();
  }

  const contentHtml = await marked(post.content || '');

  return (
    <>
      <Link href="/" className="govuk-back-link">
        Back to all posts
      </Link>

      <div className="govuk-grid-row">
        <div className="govuk-grid-column-two-thirds">
          <span className="govuk-caption-xl">
            {post.service?.title || 'Design History'}
          </span>
          <h1 className="govuk-heading-xl">{post.title}</h1>

          <p className="govuk-body-l">{post.description}</p>

          <dl className="govuk-summary-list">
            <div className="govuk-summary-list__row">
              <dt className="govuk-summary-list__key">Published</dt>
              <dd className="govuk-summary-list__value">
                {post.publishDate && format(new Date(post.publishDate), 'd MMMM yyyy')}
              </dd>
            </div>
            {post.author && (
              <div className="govuk-summary-list__row">
                <dt className="govuk-summary-list__key">Author</dt>
                <dd className="govuk-summary-list__value">{post.author}</dd>
              </div>
            )}
            {post.service && (
              <div className="govuk-summary-list__row">
                <dt className="govuk-summary-list__key">Service</dt>
                <dd className="govuk-summary-list__value">
                  {post.service.title}
                </dd>
              </div>
            )}
            {post.tags && post.tags.length > 0 && (
              <div className="govuk-summary-list__row">
                <dt className="govuk-summary-list__key">Tags</dt>
                <dd className="govuk-summary-list__value">
                  {post.tags.map((tag: any, index: number) => (
                    <span key={tag.id}>
                      {tag.name}
                      {index < post.tags.length - 1 && ', '}
                    </span>
                  ))}
                </dd>
              </div>
            )}
          </dl>

          <hr className="govuk-section-break govuk-section-break--xl govuk-section-break--visible" />

          <div 
            className="post-content govuk-body" 
            dangerouslySetInnerHTML={{ __html: contentHtml }}
          />
        </div>
      </div>
    </>
  );
}

