/**
 * Post Detail Page
 * Generated by Cursor
 */

import { notFound } from 'next/navigation';
import Link from 'next/link';
import { draftMode } from 'next/headers';
import { getPost, getPostPreview } from '@/lib/strapi';
import { format } from 'date-fns';
import { marked } from 'marked';

export default async function PostPage({ 
  params,
  searchParams 
}: { 
  params: Promise<{ slug: string }>;
  searchParams: Promise<{ preview?: string }>;
}) {
  const { slug } = await params;
  const search = await searchParams;
  const { isEnabled: isDraftMode } = await draftMode();
  
  // Use preview mode if draft mode is enabled or preview param is present
  const isPreview = isDraftMode || search.preview === 'true';
  
  const post = isPreview 
    ? await getPostPreview(slug, true)
    : await getPost(slug);

  if (!post) {
    notFound();
  }

  const contentHtml = await marked(post.content || '');

  return (
    <div className="govuk-width-container">
      <div className="govuk-breadcrumbs">
        <ol className="govuk-breadcrumbs__list">
          <li className="govuk-breadcrumbs__list-item">
            <Link className="govuk-breadcrumbs__link" href="/">
              Home
            </Link>
          </li>
          {post.service && post.service.data && (
            <li className="govuk-breadcrumbs__list-item">
              <Link className="govuk-breadcrumbs__link" href="/">
                {post.service.data.attributes.title}
              </Link>
            </li>
          )}
          <li className="govuk-breadcrumbs__list-item" aria-current="page">
            {post.heading}
          </li>
        </ol>
      </div>

      <main className="govuk-main-wrapper" id="main-content" role="main">
        <div className="govuk-grid-row">
          <div className="govuk-grid-column-two-thirds">
            <h1 className="govuk-heading-xl">{post.heading}</h1>

            <p className="govuk-body-l dh-lede">{post.description}</p>

            <p className="govuk-body-s dh-post-meta">
              {post.author && (
                <>
                  <span className="dh-post-meta__author">By {post.author}</span>
                  <br />
                </>
              )}
              Last updated: {post.publishDate && format(new Date(post.publishDate), 'd MMMM yyyy')}
            </p>

            <hr className="govuk-section-break govuk-section-break--m govuk-section-break--visible" />

            <div 
              className="dh-post-content" 
              dangerouslySetInnerHTML={{ __html: contentHtml }}
            />

            <hr className="govuk-section-break govuk-section-break--l govuk-section-break--visible" />

            {/* Tags section */}
            {post.tags && (Array.isArray(post.tags) ? post.tags : post.tags.data)?.length > 0 && (
              <div className="dh-tags">
                <h2 className="govuk-heading-s">Tags</h2>
                <ul className="dh-tags__list">
                  {(Array.isArray(post.tags) ? post.tags : post.tags.data).map((tag: any) => (
                    <li key={tag.id} className="dh-tags__item">
                      {tag.attributes?.name || tag.name}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}


