/**
 * Strapi API Helper
 * Generated by Cursor
 */

const STRAPI_URL = process.env.NEXT_PUBLIC_STRAPI_URL || 'http://localhost:1337';

interface StrapiResponse<T> {
  data: T;
  meta?: {
    pagination?: {
      page: number;
      pageSize: number;
      pageCount: number;
      total: number;
    };
  };
}

export async function fetchAPI<T>(
  path: string,
  options: RequestInit = {},
  draft: boolean = false
): Promise<T> {
  const url = `${STRAPI_URL}/api${path}`;
  
  const response = await fetch(url, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
    next: draft ? { revalidate: 0 } : { revalidate: 60 }, // No cache in draft mode
    cache: draft ? 'no-store' : 'default',
  });

  if (!response.ok) {
    throw new Error(`API error: ${response.statusText}`);
  }

  return response.json();
}

export async function getPostPreview(slug: string, isDraft: boolean = false) {
  const statusParam = isDraft ? '&publicationState=preview' : '';
  const response = await fetchAPI<StrapiResponse<any[]>>(
    `/posts?filters[slug][$eq]=${slug}&populate=*${statusParam}`,
    {},
    isDraft
  );
  const post = response.data[0];
  if (post) {
    post.title = post.Guidance || post.title;
  }
  return post;
}

export async function getPosts() {
  const response = await fetchAPI<StrapiResponse<any[]>>(
    '/posts?populate=*&sort=publishDate:desc'
  );
  // Map Guidance field to title for display
  return response.data.map((post: any) => ({
    ...post,
    title: post.Guidance || post.title,
  }));
}

export async function getPost(slug: string) {
  const response = await fetchAPI<StrapiResponse<any[]>>(
    `/posts?filters[slug][$eq]=${slug}&populate=*`
  );
  const post = response.data[0];
  if (post) {
    post.title = post.Guidance || post.title;
  }
  return post;
}

export async function getTeams() {
  const response = await fetchAPI<StrapiResponse<any[]>>(
    '/teams?populate=*'
  );
  return response.data;
}

export async function getServices() {
  const response = await fetchAPI<StrapiResponse<any[]>>(
    '/services?populate=*'
  );
  return response.data;
}

export async function getServicePosts(serviceSlug: string) {
  const response = await fetchAPI<StrapiResponse<any[]>>(
    `/posts?filters[service][slug][$eq]=${serviceSlug}&populate=*&sort=publishDate:desc`
  );
  return response.data;
}

export async function getTeamPosts(teamSlug: string) {
  const response = await fetchAPI<StrapiResponse<any[]>>(
    `/posts?filters[service][team][slug][$eq]=${teamSlug}&populate=*&sort=publishDate:desc`
  );
  return response.data;
}


